### ISSUE TITLE
Filter by date doesn't have correct result

### ISSUE THREAD

**Issue by icytailovo** [linqiu0-0/DubLease#16]
**Describe the bug**

**To Reproduce**
1. Login in and route to home page
2. Click on 'Start Date' filter and select January 2023
3. Click 'apply filter' button 
5. we see that no results found

**Expected behavior**
There should be valid leasing results based on this filter since some leasing info in the database starts on January 2023 or later

**Screenshots**
After applying search query:
<img width="915" alt="Screen Shot 2023-02-13 at 1 46 18 PM" src="https://user-images.githubusercontent.com/72170050/218581787-05bcd7e3-8008-4bb4-8d76-3acb36f018ba.png">

<img width="326" alt="Screen Shot 2023-02-13 at 1 45 54 PM" src="https://user-images.githubusercontent.com/72170050/218581709-191d7e8a-cc19-4ad7-b475-599791776f2b.png">

One valid lease result that starts on January 2023:
<img width="662" alt="Screen Shot 2023-02-13 at 1 44 43 PM" src="https://user-images.githubusercontent.com/72170050/218581485-1f1f5daf-2d45-48d1-b583-8ef68f6d133e.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome

**Additional context**
The problem may caused in backend date filtering

**Comment by RyanLi1028** [comment]
Addressed in commit 8eb6720
