### ISSUE TITLE
Add a go-back button for sign up page

### ISSUE THREAD

**Issue by zhinuoli** [linqiu0-0/DubLease#51]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when the webpage does not provide a button to back to the previous page. The sign up page has this kind of issue. If the user realize that they already have an account after clicking on the sign up for an account button, they cannot simple go back to the previous page using a button on the page. User has to click on the go-back button provided by chrome.

**Describe the solution you'd like**
Adding a go-back button on the sign up page would be helpful.

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/64811271/222624769-d2e84ac5-dbbb-43c1-af1a-e8449ef35f15.png)

**Comment by AlNahean** [comment]
just add another button under sign up with a or dividing them. The button will link to the sign in/log in page. In addition you don't wanna say welcome back in sign up page. I guess it is better suited  for log in page.
